# .github/workflows/daily.yml
name: Daily Insights
on:
  schedule:
    - cron: '0 9 * * *'  # 9 AM UTC
  workflow_dispatch:

jobs:
  generate-insights:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run insights generation
        run: python scheduler.py
        timeout-minutes: 5