name: Daily Numerology Insights

on:
  schedule:
    - cron: '0 9 * * *'  # 9 AM UTC daily
  workflow_dispatch:     # Allow manual runs

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          
      - name: Install dependencies
        run: |
          pip install plotly numpy streamlit schedule
          
      - name: Generate insights
        run: python daily_insight.py
        
      - name: Save report
        uses: actions/upload-artifact@v3
        with:
          name: numerology-report
          path: numerology_report_*.html